In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from skfeature.function.statistical_based import CFS

In [4]:
geno = pd.read_csv("C:/Users/liu.yuan/OneDrive - North Dakota University System/Research/GenomicPredictionWithNeuralNetwork/numeric_geno_rrBLUP_Imputed.csv"
                   ,sep = ",",index_col=0)
pheno = pd.read_csv("C:/Users/liu.yuan/OneDrive - North Dakota University System/Research/GenomicPredictionWithNeuralNetwork/2012-2017 BLUPs for all traits.txt"
                   ,sep = "\t",index_col=0)

In [5]:
pheno.columns.values

array(['DurumID', 'GY', 'TWT', 'TKW', 'SEDV', 'SEMEXT', 'SEMPRO', 'SEMCOL',
       'KN', 'KNUM'], dtype=object)

In [6]:
genoIndex = geno.index
phenoIndex = pheno.index
availableIndex = genoIndex.intersection(phenoIndex)

In [7]:
geno = geno.loc[availableIndex,]
pheno = pheno.loc[availableIndex,]

In [8]:
geno.index.str.contains("^AYT17") # testing

array([False, False, False, ...,  True,  True,  True], dtype=bool)

In [9]:
#geno.index.str.contains("^(?!AYT17.*$).*") # training; regular expression solution too complex
~geno.index.str.contains("^AYT17") # traing; directly invert the array

array([ True,  True,  True, ..., False, False, False], dtype=bool)

In [10]:
genoTraining = geno.loc[~geno.index.str.contains("^AYT15"),]
phenoTraining = pheno.loc[~geno.index.str.contains("^AYT15"),"SEDV"]
genoTesting = geno.loc[geno.index.str.contains("^AYT15"),]
phenoTesting = pheno.loc[geno.index.str.contains("^AYT15"),"SEDV"]

In [11]:
ridgeRegression = Ridge(alpha=0.01,max_iter = 10000)

In [12]:
ridgeRegression.fit(genoTraining,phenoTraining)

Ridge(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=10000,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [13]:
np.corrcoef(phenoTesting,ridgeRegression.predict(genoTesting))

array([[ 1.        ,  0.42984379],
       [ 0.42984379,  1.        ]])

In [37]:
%%time
numOfMarker = 100
numOfLine   = 50
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 17.1 s


In [38]:
%%time
numOfMarker = 500
numOfLine   = 50
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 13min 35s


In [39]:
%%time
numOfMarker = 500
numOfLine   = 100
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 32min 59s


In [40]:
%%time
numOfMarker = 500
numOfLine   = 200
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 25min 37s


In [41]:
%%time
numOfMarker = 1500
numOfLine   = 200
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 7h 17min 24s


In [42]:
%%time
numOfMarker = 2500
numOfLine   = 200
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 19h 26min 30s


In [ ]:
%%time
numOfMarker = 2500
numOfLine   = 300
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))

Wall time: 1d 20h 27min 41s


In [ ]:
%%time
numOfMarker = 4000
numOfLine   = 300
CFS.cfs(np.asarray(genoTraining.iloc[range(numOfLine),range(numOfMarker)]),np.asarray(phenoTraining[0:numOfLine]))